apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: ${cluster_name}
spec:
  kafka:
    version: 3.5.1
    replicas: 2
    authorization:
      type: simple
    listeners:
      - name: secure
        port: 9092
        type: ingress
        tls: true
        configuration:
          bootstrap:
            host: bootstrap.${cluster_name}.${kube_ip}.nip.io
          brokers:
          - broker: 0
            host: broker-0.${cluster_name}.${kube_ip}.nip.io
          - broker: 1
            host: broker-1.${cluster_name}.${kube_ip}.nip.io
    config:
      offsets.topic.replication.factor: 2
      transaction.state.log.replication.factor: 2
      transaction.state.log.min.isr: 1
      default.replication.factor: 2
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.5"
      allow.everyone.if.no.acl.found: "true"
    storage:
      type: ephemeral
  zookeeper:
    replicas: 2
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
